### ISSUE TITLE
XWiki "Login with Google" Fails

### ISSUE THREAD

**Issue by ashokmurthy13** [xwikisas/application-googleapps#10]
**Installed Versions:**

XWiki: 9.11.7

Google Apps Integration (Pro):  2.3.4

**Problem Statement:**

Configured Google Apps Integration(Pro) for XWiki. Able to see "Login with Google" in the login page.

When clicked "Login with Google" it redirects to "Sign in with Google". Once the credentials are entered, click the Login page, it redirects to the same login main page.

**Redirected URL:**

http://www.testxwiki.com:8080/bin/login/XWiki/XWikiLogin?srid=CsCNao2l&xredirect=%2Fbin%2Fadmin%2FXWiki%2FXWikiPreferences%3Feditor%3Dglobaladmin%26section%3DXWiki.ExtensionHistory%26srid%3DCsCNao2l

**Comment by mflorea** [comment]
The only way I managed to reproduce this is by installing the [Active Directory Application](https://store.xwiki.com/xwiki/bin/view/Extension/ActiveDirectoryApplication) and the reason is that this application overwrites the configured authenticator. So even though you put this in ``xwiki.cfg``, as indicated in the [documentation](https://store.xwiki.com/xwiki/bin/view/Extension/GoogleAppsIntegration#HActivateGoogleAuthentication):

    xwiki.authentication.authclass=com.xpn.xwiki.user.impl.xwiki.GroovyAuthServiceImpl
    xwiki.authentication.groovy.pagename=xwiki:GoogleApps.AuthService

if you execute this code in wiki page:

    {{velocity}}$xwiki.getXWiki().getAuthService(){{/velocity}}

the output is

    com.xwiki.activedirectory.internal.ActiveDirectoryAuthServiceImpl

because [``ActiveDirectorySetupListener``](https://github.com/xwikisas/application-activedirectory/blob/master/application-activedirectory-api/src/main/java/com/xwiki/activedirectory/internal/ActiveDirectorySetupListener.java) overwrites the configured authenticator.

You need to uninstall the "Active Directory **Authenticator**" extension. Note that uninstalling only the "Active Directory **Application**" is not enough because the **authenticator** is a dependency of the **application** and the Extension Manager doesn't uninstall the dependencies when you uninstall the application. Once you do this the Velocity code above should output:

    com.xpn.xwiki.user.impl.xwiki.GroovyAuthServiceImpl

If this is the case then clear the cookies associated to the domain used by your XWiki instance and try again to sign in with Google.

**Comment by azelezni** [comment]
This is still not working, I don't have the "Active Directory Authenticator" extension installed but still keep getting redirected to the same login page over and over.
`{{velocity}}$xwiki.getXWiki().getAuthService(){{/velocity}}` does show `com.xpn.xwiki.user.impl.xwiki.GroovyAuthServiceImpl`

Xwiki version 12.7.1

**Comment by polx** [comment]
Which version of googleapps do you have?
The log should be a bit more explicit now as this infinite redirect may happen in so ridiculous situations as an empty or wrong client-secret.
thanks in advance.
Paul

**Comment by AndreeaChi** [comment]
Hi! I tested the Login with Google option on a 13.10.5 Cloud XWiki, Windows 11, Google Apps Integration Pro 2.5.2 and it works well from both a main wiki and a subwiki.
