### ISSUE TITLE
Drive macro does not work on subwikis

### ISSUE THREAD

**Issue by oanat** [xwikisas/application-googleapps#54]
Steps to reproduce:
* install and configure the 2.4.7 version of GoogleApps with XWiki 11.10.5 in the main wiki
* create a subwiki 
* go to the subwiki and create a new page
* insert the global Google Drive macro on the new page on the subwiki

Result
* the page displays an error on the subwiki
<img width="1042" alt="SubwikiError" src="https://user-images.githubusercontent.com/370535/90772044-c7cda300-e2fc-11ea-90d0-ab1ba43c0e24.png">

Expected Result:
* the page displays the form to search and embbed Google Drive documents similar to the main wiki
<img width="1021" alt="MainWikiMacro" src="https://user-images.githubusercontent.com/370535/90772113-e338ae00-e2fc-11ea-8f14-82ad650df828.png">

**Comment by oanat** [comment]
I also have tried to install the application on the subwiki as well. Next, I got an error from Google to add the proper redirect on the https://console.developers.google.com/. I added http://apps.xwiki.com:8080/xwiki/wiki/solutions/view/GoogleApps/OAuth and the inserting the drive macro on a wiki page looked good afterwords. However, when I tried to search for something in the drive, it displayed a different error:
<img width="812" alt="SubwikiDriveError" src="https://user-images.githubusercontent.com/370535/90775470-90adc080-e301-11ea-8809-d1ca413b0791.png">
Since the drive macro is a global macro, shouldn't it work without the need to install the app on the subwiki? Or this is really needed by the Google configuration?

**Comment by AndreeaChi** [comment]
Hi! Happy to say that the issue is not reproducing anymore with the Google Apps Integration Pro version 2.5.2.

1. On a hosted XWiki instance 13.10.5, I have installed on farm Google Apps Integration Pro version 2.5.2.
2. I have then configured the app on both the main wiki and the subwiki with the same credentials added in a project created on the Google Console, based on [this documentation](https://store.xwiki.com/xwiki/bin/view/Extension/GoogleAppsIntegration#installation)
3. Then, on a Sandbox test page, I inserted the Google Drive Macro. 
Result of the insert in inline editing mode:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/36840106/185128864-f0466301-a8f3-4ec6-9635-dc963be81c08.png">
Result of the insert in WYSIWYG editing mode:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/36840106/185129363-e4106cf1-a0d1-48ea-9b05-9eadd4637d12.png">

4. Finally, I have searched a document in the drive and there was a successful result:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/36840106/185130060-112e362c-335f-412c-9fe8-66da3b43314f.png">

I then embedded one of the files from the shown list:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/36840106/185130505-b52d3d75-d68d-45ab-ba02-9a502de94965.png">
