### ISSUE TITLE
Add a small description for the options displayed on Google Apps Integration Configuration

### ISSUE THREAD

**Issue by oanat** [xwikisas/application-googleapps#8]
This app is quite technical to setup and we should help the user understand the effect for each option.

**Comment by polx** [comment]
I'm proposing the explanations in the attached screenshot:

<img width="615" alt="g-apps-config-2019-02-12" src="https://user-images.githubusercontent.com/818835/52616696-a5ea9900-2e99-11e9-8ee6-7463a8fb7374.png">

Some of them may need verification, in particular the cookies-based fields for which my explanation base on reading the code. After verification, I would like to adjust config screen JS, so that the cookies adjustments are inactive in case the cookies are not enabled. I wonder, however, if there are administrators who deactivate explicitly the cookies.

How understandable do the explanations feel?
I've translated them to French too.

**Comment by polx** [comment]
As the PR comments suggested to write my own configuration UI, I took the opportunity to structure the UI in two sections ("communication with google services" and "xwiki login behaviour") and to add JavaScript to deactivate fields if the overall activation is not there.

Both of these these are visible in the screenshot.
<img width="578" alt="gapps-config-with-structure" src="https://user-images.githubusercontent.com/818835/53036716-96121c80-3478-11e9-8a05-168e52e49366.png">

To me, this presentation would solve this issue. Can I get a confirmation?

**Comment by mflorea** [comment]
The screenshot looks good! @silviamacovei @oanat WDYT?

**Comment by oanat** [comment]
I agree, the screenshot looks great!

**Comment by silviamacovei** [comment]
Very nice proposal. Thank you!
